### ISSUE TITLE
I keep getting an error on Email+

### ISSUE THREAD

**Issue by jbarber2015** [continuousit/seq-apps#10]
I am using EmailPlus app in Seq, but when I try to log an error, I keep getting this error.  Looks like a problem  with template.  Any ideas?
  The event event-c5b937eff46308d20b00000000000000 could not be sent to Email Errors. 

AppId
hostedapp-5 
AppInstanceId
appinstance-12
 
AppInstanceTitle
Email Errors
 
EventId
 event-c5b937eff46308d20b00000000000000
   System.NullReferenceException: Object reference not set to an instance of an object.
   at Seq.App.EmailPlus.EmailReactor.FormatTemplate(Func`2 template, Event`1 evt, Host host)
   at Seq.App.EmailPlus.EmailReactor.On(Event`1 evt)
   at Seq.Server.Features.Runner.AppHost.SendLogEventData(ISubscribeTo`1 reactor, DateTime utcTimestamp, Int64 arrivalOrder, UInt32 hash, String document)
   at Seq.Server.Features.Runner.AppHost.Send(StorageEvent storageEvent)

**Comment by nblumhardt** [comment]
Hi @jbarber2015 - thanks for getting in touch.

Not sure if any recent bug fixes have touched this area - can you please let me know which version of the Email+ app this is, and in which version of Seq?

If you are able to supply (even a redacted version of) your email template this might help track things down (or are you using the default?).

Thanks again for the report!

**Comment by jbarber2015** [comment]
I have Seq 2.42 with EmailPlus 1.0.24.  I am using no body template (default).  I setup a signal which was @Level == "Error" || @Level == "Fatal", and so on any error I would get an email.  I downloaded another app which is Seq.App.Email and configured it exactly the same, and don't get the error.

**Comment by nblumhardt** [comment]
Hi Jonathan,

I've reproduced this - the error occurs when the event being sent to it has no associated properties. I'll post a fix to the EmailPlus app shortly.

In the meantime as a workaround, you can add:

```
    .Enrich.WithMachineName()
```

to your Serilog configuration so that at least one property is attached.

Regards,
Nick

**Comment by nblumhardt** [comment]
Version 1.0.25 is now available with this change.
