### ISSUE TITLE
"View in Seq" Email Links Broken

### ISSUE THREAD

**Issue by bbrandt** [continuousit/seq-apps#11]
"View in Seq" links in emails do not work.  

Id string value is missing the quotes:
`@Id==event-c097a9fd161908d348162a0000000000`
Should be:
`@Id=="event-c097a9fd161908d348162a0000000000"`

**Comment by nblumhardt** [comment]
Hi Ben, thanks for the report!

Is this the link in the Email+ app below?

![image](https://cloud.githubusercontent.com/assets/342712/12155990/0a7db274-b514-11e5-84c4-37b37a108a60.png)

It seems to produce the correct link for me:

![image](https://cloud.githubusercontent.com/assets/342712/12156064/6b42365c-b514-11e5-893d-3a331a3f2910.png)

The source has the double quotes in there:

https://github.com/continuousit/seq-apps/blob/master/src/Seq.App.EmailPlus/Resources/DefaultBodyTemplate.html#L139

Am I looking at the wrong one?

**Comment by bbrandt** [comment]
I see the link with quotes when I mouse over it in Outlook, but when I click the link and it does to Chrome, my default browser, the quotes get dropped.  Does this need to have %22 instead of "?  Or does it need some sort of escape sequence for the quote characters?

**Comment by nblumhardt** [comment]
Second thing I've learned today! My test clients (Gmail and Fastmail) both accept " in URLs, but the standard forbids them. Fixing now....

**Comment by nblumhardt** [comment]
Fixed on master, new build should be on the way through CI. Thanks!
