### ISSUE TITLE
Support multiple Recipients

### ISSUE THREAD

**Issue by laurencee** [continuousit/seq-apps#16]
It's pretty common to want to send emails to more than 1 recipient at a time without having to create a new instance for every email address.

Typically you just separate multiple recipients with ; in the "To" section of the email.

The code change would be simply; after creating the mail message, split on ";" and looping through the splits to add the recipients to the mail message "To" collection.
https://github.com/continuousit/seq-apps/blob/master/src/Seq.App.Email/EmailReactor.cs#L89

I'll create a pull request for this later today.

**Comment by laurencee** [comment]
I'm an idiot, can just use a comma to separate recipients.

**Comment by normanhh3** [comment]
Just got bit by not supporting ";", thanks to this issue though, I resolved it myself.  Might be worth a PR to include a bit of documentation in the UI that indicates multiple recipients are entered with comma separators.

**Comment by laurencee** [comment]
Nice change, that should help others out in the future who run into the same issue.

Wonder how many people do this? Might actually be worth supporting ';' as a separator.
